FILE_LOCATION=/file/CLIENTES_IN_0425.dat
USE_TEST_DATABASE=false

NODE_ENV=production

DB_HOST=db
DB_PORT=1433
DB_USER=sa
DB_PASSWORD=YourStrong!Passw0rd
DB_NAME=persons_database
DB_TRUST_SERVER_CERTIFICATE=true
HTTP_SERVER_PORT=3000
HTTP_SERVER_HOSTNAME=0.0.0.0
AUTO_START_PROCESS=0
